### ISSUE TITLE
Request for Forge Version

### ISSUE THREAD

**Issue by SamJBarney** [Deadrik/TFCraft#742]
I'm writing a scripting interface for TFCraft to make it easy to use in CustomNPCs scripting environment. I was just wondering which version of Forge you are using for development, because I tried to pull the code from here, and when I dropped it in, it was throwing all kinds of errors.

Sorry about this random post. I was going to open a thread on the forums, but I wasn't allowed to do so.

**Comment by emris** [comment]
This file will give you answers :)
https://github.com/Deadrik/TFCraft/blob/master/build.prop
