### ISSUE TITLE
Is it possible to remove certain recipe via a MineTweaker-Addon?

### ISSUE THREAD

**Issue by 3TUSK** [Deadrik/TFCraft#763]
Sorry for bothering you. Currently I am working on a TFCraft-MineTweaker3 cross-mod which allow modpack creator to add some custom recipes in TFC quern, anvil, barrel and etc. 

While I am writing code I notice that it seems possible to remove some quern recipe by removing the recipe from List<QuernRecipe> (also remove the itemstack from List<ItemStack> vaildItem). 
I am not sure whether TFCraft has such a rule that anyone cannot tweak the recipe because it can break the tech-tree, or the whold "system".  Same thing appears on kiln and  barrel.

Since I cannot figure out, then I decide to open this issue.
Thanks for your time, and I hope I'll get answer soon. Also I am sorry for poor English.

**Comment by Kittychanley** [comment]
We have our own recipe registry for quern recipes. It is currently not possible to remove them without creating an addon, since Minetweaker can only remove recipes from the crafting recipe registry, not the quern recipe registry. If you'd like this functionality, you'll need to contact somebody over at modtweaker to add TFC compatibility.

**Comment by 3TUSK** [comment]
Seems I didn't say it clearly... 
Well, I made an add-on mod to allow MineTweaker to add or remove quern recipe. Currently situation is that I can add new quern recipe, but the remove function doesn't work.

**Comment by Kittychanley** [comment]
You realize that there is already something called modtweaker that you are supposed to use for Minetweaker functionality on non-vanilla things right?

**Comment by 3TUSK** [comment]
But the thing is that There is no support for TFCraft in ModTweaker2. 
ModTweaker2: https://github.com/jaredlll08/ModTweaker2

**Comment by Kittychanley** [comment]
Right. But it's open source. So fork it and add support.

**Comment by 3TUSK** [comment]
Sorry, but You misunderstand my point.
The thing is, there are some mod that not allow MineTweaker to edit their recipe, like all Reika's MOD, due to the tech-tree problem.
I want to make sure that TFCraft doesn't have such a rule.

**Comment by Kittychanley** [comment]
TFCraft does not have any rules against editing recipes. If you can find the cause of your inability to remove a recipe, we will happily fix it.

**Comment by 3TUSK** [comment]
Okay, thanks for your time again.

**Comment by Yulife** [comment]
Sorry if I'm late to the conversation but not every minetweaker mod support is handled by Modtweaker. Some mods even include Minetweaker support in their mod natively but that requires constant pull requests if the author of the support isn't staff of the mod (repo). There are also seperate mods for Modtweaker support like Gregtech 6 Support.

@3TUSK I am the documenter of Modtweaker but hit me up when you got TFC support finished so I can document it ;)

**Comment by 3TUSK** [comment]
@Yulife 
My initial idea is making a individual mod to provide MineTweaker support for TFCraft, since I have been working on a modpack including GregTech5 and TFCraft at the same time for couples of weeks, and the tech-tree issue confused me a lot. Then I did it, which seems work well.

Thanks to the conversation, I realized that it will be a better idea that integrate this small mod into ModTweaker2, which might be much helpful for modpack creator.

Currently my school is a little bit busy, but I will save time to finish the integration ASAP. If you'd like to do documentation of that, I will say appreciate to you.
If there is grammatical mistakes, forgive me please.

**Comment by Yulife** [comment]
Your English is fine and readable! :) Looking forward to it.

**Comment by 3TUSK** [comment]
@Yulife Which ModTweaker is latest? ModTweaker2 or ModTweaker-2?

**Comment by Yulife** [comment]
@3TUSK Modtweaker2 is a from-jared-continued version as joshiejack quit Modtweaker. Modtweaker-2 is a **rewritten** version of Modtweaker1. You may want to add integration into Modtweaker-2. :)

**Comment by Yulife** [comment]
Oops, please PR to Modtweaker2 repo, the non rewritten version.
