### ISSUE TITLE
All biomes are "Lake"

### ISSUE THREAD

**Issue by Paul17041993** [Deadrik/TFCraft#801]
Using the standard way to obtain a biome in the world results in the same biome being returned everywhere, which appears to be the last biome in TFCBiome, LAKE as "Lake".

**Comment by ADHalek** [comment]
You're going to have to be more specific. What is this "standard way to obtain biome"? Because F3 shows the proper biome.

**Comment by Kittychanley** [comment]
You're going to have to be more specific. What is this "standard way to obtain biome"? Because F3 shows the proper biome.

**Comment by Paul17041993** [comment]
nvm, just realised what I was doing, it just looked like it was stuck on the last biome due to it being identical for a range of coords and so happened to be the last biome in the list.

I was referring about the function call though, world.getBiomeGenForCoords(x,z)
