### ISSUE TITLE
[Suggestion] More food from calamari 

### ISSUE THREAD

**Issue by rjdunlap** [Deadrik/TFCraft#809]
https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Entities/Mobs/EntitySquidTFC.java#L68

Right now its 0.5oz - 1.5oz

http://www.clovegarden.com/ingred/seasquidc.html

IRL : about 6-1/8 ounces (38%) of cleaned bodies and 3-1/3 ounces (21%) of tentacles, making a total yield of 9-3/8 ounces (59%).

**Comment by Kittychanley** [comment]
You missed the fact that that's a pound of 1 oz squids. I.e. the yields of 16 squids.

**Comment by Kittychanley** [comment]
Please use the suggestions forum for posting suggestions. This tracker is explicitly for bugs in the latest dev commits.
