### ISSUE TITLE
TFC Stone Declared as replaceable?

### ISSUE THREAD

**Issue by Muramasa-** [Deadrik/TFCraft#810]
Would it be possible to change the TFC stone to replaceable so other mods can support populating the world with ore?

Original issue on GT5U page: https://github.com/Blood-Asp/GT5-Unofficial/issues/255

Thanks for your time.

**Comment by Kittychanley** [comment]
No. That's how we keep vanilla ores from generating. If you want mod ores in TFC worlds, that's what the TFCOre.cfg file is for.

**Comment by Muramasa-** [comment]
I understand you can add new ore via the config, but it would be nice to have TFC content/mechanics along with other mods that also handle ore gen.

It would be really nice to be able to use TFC with big packs, now of course I'm no modder so I don't know how difficult it actually is but it seems like it would be an easy change to allow TFC blocks to be replaceable.

However you have already closed the issue so I guess that's that.

**Comment by Kittychanley** [comment]
The replaceable flag is what vanilla blocks use for world generation. If we switch our blocks to be replaceable, then all vanilla ores will generate in our world, which we explicitly do not want.

**Comment by Muramasa-** [comment]
May I suggest a config option that toggles this effect?

So if players like myself (and many others) want to play with TFC with other ore then having Vanilla ore as a side effect would be our problem. I think a lot of people would be ok with that downside.

**Comment by Kittychanley** [comment]
You can already have the other ore though, and you can have it actually generating in such a way that you might actually be able to find it without strip mining because you can specify height and stone type.

Adding ores to the TFCOres.cfg file is not hard.

**Comment by Muramasa-** [comment]
No it's not hard... and I will end up doing that if I have to.

But it just seems like a simple addition that can make TFC have great compatibility with other mods. Having a giant warning that it would turn vanilla ore gen back on should be good enough and players to understand.

The reason I made this issue is because I thought that it could of been a simple way to improve TFC compatibility with all ore gen and it would make it a lot easier for pack makers and players to make their own experience.

Anyway this doesn't seem to be going anywhere. Thanks for taking the time to discuss it anyway.

**Comment by Kittychanley** [comment]
You do realize that most mod ores have a relatively low height for spawning, right? And the fact that TFC sea-level is all the way up at y=140? So even if we did enable this option, you'd have to dig through hundreds of blocks of stones before you would even get close to deep enough to even find the ores.

Either way you're going to have to edit some sort of config file to get things actually working. Why not just edit the config file that's already been provided?

**Comment by Muramasa-** [comment]
Because this was a suggestion to improve compatibility without having to add each and every ore into a config and have to re-create the way that ore spawns from the specific mod that adds it and there doesn't seem like a technical reason why it couldn't exist. (of course correct me if there is)

One of the best things about modded Minecraft is compatibility. And I see a great way to make this mod compatible with all ore gen. And I think players really wouldn't mind the discussed downsides.

You're already willing to help BloodAsp with generating GT5U ore because it uses Tile Entities. Having this option would make it so every normal ore gen mod was compatible.

**Comment by Kittychanley** [comment]
By limiting ore generation to only blocks that are listed in the TFCOre.cfg file, we are able to make it so that the prospector's pick will work with all of those ores. Without that, you will be digging blindly for mod ores.

**Comment by Muramasa-** [comment]
I don't anyone would expect the prospectors pick to work if this this change was in place.

**Comment by Kittychanley** [comment]
Having the prospector's pick work for mod ores has been our #1 request from mod pack authors for a long time.

**Comment by Muramasa-** [comment]
I meant if TFC was marked as replaceable. Not generally.

Again, this doesn't seem to be going anywhere as you seem to have your decision made. Thanks for taking the time.
