### ISSUE TITLE
[BUG] [CRASH] Crashes when pressing 'U' in NEI on some fruits, can't make cider and etc.

### ISSUE THREAD

**Issue by dobegor** [Deadrik/TFCraft#816]
Can't make any alcohol out of fruits, it also crashes when pressing 'U' (NEI show item usage option) on any fruit.

Logfile attached (tl;dr: latest TFC, some weird exceptions around fruit item).
[ForgeOptiFine 1.7.10 (Dec 12, 2015 11:30:13 PM).txt](https://github.com/Deadrik/TFCraft/files/60268/ForgeOptiFine.1.7.10.Dec.12.2015.11.30.13.PM.txt)

UPDATE: it also crashed using potato. I want vodka. Plz fix asap.

**Comment by dobegor** [comment]
Err. It seems something went definetly wrong.
There is a full vessel of fresh water and 160 oz of cornmeal with no decay.
What's wrong?
![image](https://cloud.githubusercontent.com/assets/14029650/11764051/52e87222-a12a-11e5-99c2-971e944c931d.png)

**Comment by Kittychanley** [comment]
The only thing wrong here is user error. You've put waaaay too much food into the barrel. You only need 40 oz of food for a full water barrel.

http://wiki.terrafirmacraft.com/Barrel#Alcohol

"The food weight is the limiting factor in this recipe, meaning that for every 1,000 mB of fresh water in the barrel, there must be at least 4 ounces of food in the input slot. "

**Comment by Kittychanley** [comment]
The crash has already been fixed by 2b3a238f58d3b06f3c5f4bd540dad04c004abc2b

Please only use this tracker for bugs that are in the current development branch, not the latest release.

**Comment by dobegor** [comment]
@Kittychanley sorry, didn't tried the dev branch. Also thx ofr the info.
