### ISSUE TITLE
Ticking memory connection

### ISSUE THREAD

**Issue by lightning02** [Deadrik/TFCraft#821]
This happened incidentally when looking in creative container GUI 
http://pastebin.com/VY3h7JJ5

**Comment by Kittychanley** [comment]
There's nothing I can do without the full crash report. Also, we don't offer support for creative mode.

**Comment by lightning02** [comment]
Oh... well... in this case I don't make you waste your time.. after all is not a recurrent crash, I'll be fine..  I think :l
I'm gonna close this then
